### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by luis-soares-sky** [rokucommunity/vscode-brightscript-language#230] opened 2020-05-04 17:40 UTC
We're noticing consistently high processing times, and the process will keep running even after closing VS Code.

<img width="852" alt="Screenshot 2020-05-04 at 18 26 42" src="https://user-images.githubusercontent.com/57358121/80994618-d3bc5480-8e34-11ea-9f0b-c8176cf96665.png">

---

- Issue Type: `Performance`
- Extension Name: `brightscript`
- Extension Version: `2.1.11`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.44.2`

---

- CPU Profile: [celsoaf.brightscript-unresponsive.cpuprofile.txt](https://github.com/rokucommunity/vscode-brightscript-language/files/4575800/celsoaf.brightscript-unresponsive.cpuprofile.txt)
- Stuck process (log that a colleague of mine sent): [Sample of Code Helper (Renderer).txt](https://github.com/rokucommunity/vscode-brightscript-language/files/4575807/Sample.of.Code.Helper.Renderer.txt)

**Comment by TwitchBronBron** [comment] 2020-05-04 19:09
Thanks! This is very helpful. I'll try and dig into this to see if I can narrow down the cause of the issues. 

In the mean time, if you are unable to work, you can disable the language server with a user/workspace setting. However, that will obviously remove any inline parse checking.

**Comment by TwitchBronBron** [comment] 2020-05-04 19:10
Sorry, forgot to mention which setting. 

Set `brightscript.enableLanguageServer` to false to disable it completely.

**Comment by TwitchBronBron** [comment] 2020-05-05 20:14
There is definitely a performance issue, introduced after 0.8.2. I ran a few benchmarks, and I think that I have some fixes. If my fixes didn't break anything else, then I have actually doubled the performance of the parser since 0.8.2. 

![image](https://user-images.githubusercontent.com/2544493/81108168-46d1d380-8ee6-11ea-9d3a-ae3fc154e8be.png)

I have the fix local, and will release it after a little bit more testing, hopefully sometime tonight.

**Comment by TwitchBronBron** [comment] 2020-05-06 10:48
@luis-soares-sky, extension version 2.1.14 includes these changes. Can you please try it again and see how it works for you? Also if you have a chance, compare 2.1.14's performance to 2.1.9 (the last release without the performance bugs) and see if it has improved at all.

**Comment by luis-soares-sky** [comment] 2020-05-06 20:26
I don't know how to take metrics like the ones you posted, but it's safe to say that I'm not getting hanging processes anymore, and overall the performance feels much better. Even more so than 2.1.9 which did feel a bit sluggish in comparison.

Thank you!

**Comment by TwitchBronBron** [comment] 2020-05-07 00:02
Good to hear! The metrics I posted were from a custom benchmark script I wrote just for this. I'm working on converting it into something that GitHub Actions can run on every pull request, so that way we can catch performance regressions before they get released. :) I'm going to close this issue, but please keep us informed if you notice any other performance issues.

**Closed by TwitchBronBron** 2020-05-07 00:02 UTC
