### ISSUE TITLE
does not warn if envfile cannot be found

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/vscode-brightscript-language#175] opened 2019-07-19 00:28 UTC
I had an envFile which had a case spelling error (`devstuff/.env`, instead of `devStuff/.env`) - it was not brought to my attention, and only through debugging the extension+adapter in the vscode host, did I discover that the launchconfig, had a stray "host" value, which was what the adapter was attempting to connect to

**Comment by chrisdp** [comment] 2019-07-22 00:45
I have completed the other items I have been working on so I will attempt to work on this over the following week.

**Comment by TwitchBronBron** [comment] 2019-08-10 02:37
@georgejecook So, it appears that we have been doing a "does envFile exist" check for a while now (months). We check to see if the file exists, and throw an exception if it doesn't exist. 
See [this line](https://github.com/TwitchBronBron/vscode-brightscript-language/blob/3f1cd5a6fae3869ae6cd8fb8350a03417cc82750/src/DebugConfigurationProvider.ts#L214). 

Can you still reproduce this? If so, could you provide a sample application or reproducible steps, because whenever I try to launch debug session with a non-existent envFile path, it correctly shows an error. 

![image](https://user-images.githubusercontent.com/2544493/62816471-295a0f80-baf6-11e9-9f61-e14dafeb56c2.png)

**Comment by TwitchBronBron** [comment] 2020-03-08 01:28
@georgejecook does this still happen? If so, could you provide reproducible steps? Otherwise, can you close this issue?

**Closed** 2020-04-11 11:30 UTC
