### ISSUE TITLE
Can't build apps after 2.1.20

### ISSUE THREAD

**Issue by luis-soares-sky** [rokucommunity/vscode-brightscript-language#244] opened 2020-05-20 09:13 UTC
Using VS Code 1.45.1, Node 12.8.1, in macOS 10.14.6 (Mojave).

Given the following launch configuration...

```jsonc
        {
            "type": "brightscript",
            "request": "launch",
            "consoleOutput": "normal",
            "internalConsoleOptions": "openOnSessionStart",
            "preLaunchTask": "gulp vscPreLaunchEnv",
            "name": "Debug (.env)",
            "envFile": "${workspaceFolder}/.env",
            "host": "${env:ROKU_DEV_TARGET}",
            "password": "${env:ROKU_DEV_PASSWORD}",
            "retainStagingFolder": false,
            "stopOnEntry": false,
            "files": [
                "*",
                "*.*",
                "**/*.*"
            ],
            "rootDir": "${workspaceFolder}/build",
            "sourceDirs": [
                "${workspaceFolder}/"
            ]
        },
```

In 2.1.19 this config works, and builds run successfully.

In 2.1.20 I get an error saying **"outDir is required"** message.

![image](https://user-images.githubusercontent.com/57358121/82428389-57f01800-9a82-11ea-9607-6b11f86b2c75.png)

If I add `"outDir": "${workspaceFolder}/out"` to it, then I'll get an error saying **"connect ECONNREFUSED 127.0.0.1:8060"**.

![image](https://user-images.githubusercontent.com/57358121/82428447-70f8c900-9a82-11ea-9a3d-ee840d19c4ea.png)

**Comment by TwitchBronBron** [comment] 2020-05-20 10:51
What's strange about this is, all that changed between 2.1.19 and 2.1.20 was [some updates to the language server](https://github.com/RokuCommunity/vscode-brightscript-language/compare/v2.1.19...v2.1.20). The only part of brighterscript that is being used by the launch workflow is bsconfig.json if it exists. 

Do you have a bsconfig.json file in your project?

**Comment by luis-soares-sky** [comment] 2020-05-20 10:57
> What's strange about this is, all that changed between 2.1.19 and 2.1.20 was [some updates to the language server](https://github.com/RokuCommunity/vscode-brightscript-language/compare/v2.1.19...v2.1.20). The only part of brighterscript that is being used by the launch workflow is bsconfig.json if it exists.
> 
> Do you have a bsconfig.json file in your project?

I don't have a bsconfig.json file. The project is in the root directory, we use gulp to process and export some files into the "build/" folder, but outside of that, everything else is just standard BrightScript projects.

I've tried it on multiple projects (simple and complex) and got the same results. Reverting to 2.1.19 solves the issues.

**Comment by luis-soares-sky** [comment] 2020-05-20 11:05
![image](https://user-images.githubusercontent.com/57358121/82439062-f2a42300-9a91-11ea-9d8e-e643c2e0eb43.png)

Not sure if it helps, but it seems that in 2.1.20, the "Output" view doesn't show any of the extension logs that used to appear (Log, Debug, Language Server...)

**Comment by jean-guyrivard** [comment] 2020-05-20 14:42
Same issue, and reverting to 2.1.19 fixes the issue.
In my case the outDir, once fixed I get an error with invalid URI with http://${promptForHost}/keypress/home which probably explains the connection refused from the OP.

**Comment by chrisdp** [comment] 2020-05-20 14:44
So we found the issue. @TwitchBronBron Is planing to get a new build out tonight we the fix. 

Thanks.

**Comment by TwitchBronBron** [comment] 2020-05-20 19:44
Fixed in [v2.1.21](https://github.com/rokucommunity/vscode-brightscript-language/releases/tag/v2.1.21)

**Closed by TwitchBronBron** 2020-05-20 19:44 UTC
Labels: bug

**Comment by luis-soares-sky** [comment] 2020-05-21 08:22
Can confirm the fix. Thank you very much!

**Comment by TwitchBronBron** [comment] 2021-06-02 03:59
This has been resovled in v2.22.2 and was caused by a missing prod dependency in roku-deploy
